stages:
  - build

# 定义使用的镜像
image: node:21

# 构建阶段
build:
  stage: build
  script:
    - npm install -g pnpm
    - pnpm install
    - pnpm build
  only:
    - main
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist/
