stages:
  - install
  - build

# 定义使用的镜像
image: node:20

# 安装依赖阶段
install_dependencies:
  stage: install
  script:
    - npm install -g pnpm
    - pnpm install
  only:
    - main
  cache:
    paths:
      - node_modules/

# 构建阶段
build:
  stage: build
  script:
    - pnpm build
  only:
    - main
  artifacts:
    paths:
      - dist/
  cache:
    paths:
      - node_modules/
