stages:
  - test
  - build_frontend
  - build_image

test_agent:
  stage: test
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - kubectl config get-contexts
    - kubectl config use-context path/to/agent/project:agent-name
    - kubectl get pods
  only:
    - main

# Build frontend and generate artifacts
build_frontend:
  stage: build_frontend
  image: node:21
  script:
    - npm install -g pnpm
    - pnpm install
    - pnpm build
  rules:
    - if: $CI_COMMIT_TAG
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

# Build Docker image and push to harbor registry
build_image:
  stage: build_image
  variables:
    HARBOR_REGISTRY_IMAGE: harbor.act.buaa.edu.cn/crater/web-frontend
  image:
    name: harbor.act.buaa.edu.cn/crater/kaniko-executor:debug
    entrypoint: [""]
  script:
    # Since GitLab container registry is not enabled, we need to set up harbor registry manually.
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${HARBOR_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${HARBOR_REGISTRY_USER}" "${HARBOR_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${HARBOR_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
  dependencies:
    - build_frontend
