# nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crater-web-frontend
  namespace: crater
  labels:
    app: crater-web-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crater-web-frontend
  template:
    metadata:
      labels:
        app: crater-web-frontend
    spec:
      containers:
        - name: crater-web-frontend-container
          image: crater-harbor.act.buaa.edu.cn/crater/web-frontend:100f83f1
          ports:
            - containerPort: 80

---
# nginx-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: crater-web-frontend-svc
  namespace: crater
spec:
  selector:
    app: crater-web-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
