apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  labels:
    app: go
spec:
  selector:
    matchLabels:
      app: go
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - image: harbor.act.buaa.edu.cn/gpu-portal/backend:v3
        name: go
        command: ["./app","-v","v1.3"]
        ports:
        - containerPort: 8080
          protocol: TCP
